apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app: vault
    service: identity-service
spec:
  selector:
    service: identity-service
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
