apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: vault
    service: api-gateway
spec:
  selector:
    service: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
