import * as dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config({ path: path.resolve(process.cwd(), '../../.env') });

import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema.js';
import { mockGetEmbedding } from '@vault/mocks';
import bcrypt from 'bcryptjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim() +
    '-' +
    Math.floor(Math.random() * 10000)
  );
}

async function seed() {
  const url = process.env['DATABASE_URL'];
  if (!url) throw new Error('DATABASE_URL is not set');

  const client = postgres(url, { max: 1 });
  const db = drizzle(client, { schema });

  console.log('Seeding database...');

  // Seed users
  const passwordHash = await bcrypt.hash('Vault2024!', 12);

  const [adminUser] = await db
    .insert(schema.users)
    .values({
      email: 'admin@vault.luxury',
      passwordHash,
      role: 'admin',
      accessTier: 'level_3',
      displayName: 'VaultAdmin',
      emailVerified: true,
      kycStatus: 'approved',
      preferredCurrency: 'AED',
      preferredLanguage: 'en',
    })
    .returning()
    .onConflictDoNothing();

  const [sellerUser] = await db
    .insert(schema.users)
    .values({
      email: 'seller@vault.luxury',
      passwordHash,
      role: 'seller',
      accessTier: 'level_2',
      displayName: 'PrimeSeller',
      emailVerified: true,
      kycStatus: 'approved',
      preferredCurrency: 'AED',
      preferredLanguage: 'en',
    })
    .returning()
    .onConflictDoNothing();

  const [agentUser] = await db
    .insert(schema.users)
    .values({
      email: 'agent@vault.luxury',
      passwordHash,
      role: 'agent',
      accessTier: 'level_2',
      displayName: 'EliteAgent',
      emailVerified: true,
      kycStatus: 'approved',
      reraOrn: '1234567890',
      reraVerified: true,
      preferredCurrency: 'AED',
      preferredLanguage: 'en',
    })
    .returning()
    .onConflictDoNothing();

  const [buyerUser] = await db
    .insert(schema.users)
    .values({
      email: 'buyer@vault.luxury',
      passwordHash,
      role: 'buyer',
      accessTier: 'level_2',
      displayName: 'DiscerningBuyer',
      emailVerified: true,
      kycStatus: 'approved',
      preferredCurrency: 'USD',
      preferredLanguage: 'en',
    })
    .returning()
    .onConflictDoNothing();

  // suppress unused variable warning
  void buyerUser;

  const sellerId = sellerUser?.id ?? adminUser?.id;
  const agentId = agentUser?.id;

  if (!sellerId) {
    console.log('Users already exist, skipping seed...');
    await client.end();
    return;
  }

  console.log('Users created.');

  // 25 luxury listings
  const listingsData: Array<typeof schema.listings.$inferInsert> = [
    // ── 5 Hotels ──────────────────────────────────────────────────────────────
    {
      sellerId,
      agentId,
      title: 'The Zenith Collection — Ultra-Luxury Boutique Hotel, Dubai Creek',
      slug: slugify('zenith-collection-boutique-hotel-dubai-creek'),
      assetType: 'hotel',
      status: 'active',
      visibility: 'public',
      priceAmount: '280000000',
      priceCurrency: 'AED',
      priceOnRequest: false,
      country: 'United Arab Emirates',
      city: 'Dubai',
      district: 'Dubai Creek Harbour',
      coordinatesLat: '25.2186',
      coordinatesLng: '55.3260',
      sizeSqm: '18500',
      bedrooms: 85,
      bathrooms: 102,
      floors: 22,
      yearBuilt: 2021,
      description:
        'An iconic 85-key ultra-luxury boutique hotel positioned at the heart of Dubai Creek Harbour. This trophy asset delivers consistent double-digit NOI with a 94% average occupancy rate. Features include a rooftop infinity pool, three Michelin-starred dining concepts, and a world-class spa. Title deed clear, zero encumbrances.',
      keyFeatures: [
        '94% Avg Occupancy',
        '3 F&B Outlets',
        'Rooftop Pool',
        'Spa & Wellness',
        'Full Management Team',
        'Creek & Skyline Views',
      ],
      commercialData: { occupancyRate: 94, noi: 18500000, capRate: 6.6, revpar: 2800 },
      sellerMotivation: 'best_offers',
      titleDeedVerified: true,
      listingQualityScore: 95,
      qualityTier: 'platinum',
      daysOnMarket: 12,
    },
    {
      sellerId,
      title: 'Al Qasr Heritage Hotel — Abu Dhabi Corniche',
      slug: slugify('al-qasr-heritage-hotel-abu-dhabi-corniche'),
      assetType: 'hotel',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '420000000',
      priceCurrency: 'AED',
      priceOnRequest: false,
      country: 'United Arab Emirates',
      city: 'Abu Dhabi',
      district: 'Corniche Road',
      coordinatesLat: '24.4672',
      coordinatesLng: '54.3773',
      sizeSqm: '32000',
      bedrooms: 142,
      bathrooms: 168,
      floors: 28,
      yearBuilt: 2018,
      description:
        'A magnificent 142-key heritage-inspired luxury hotel on the Abu Dhabi Corniche. Unobstructed sea views, world-class conference facilities hosting 2,000+ delegates, and a private beach club make this an irreplaceable institutional asset. Managed by a leading international operator under a 25-year contract.',
      keyFeatures: [
        'Private Beach Club',
        'Conference Centre (2000+)',
        '4 F&B Outlets',
        'Spa',
        '25-Year Mgmt Contract',
        'Sea Views',
      ],
      commercialData: { occupancyRate: 88, noi: 26000000, capRate: 6.2, revpar: 3200 },
      sellerMotivation: 'price_flexible',
      titleDeedVerified: true,
      listingQualityScore: 92,
      qualityTier: 'platinum',
      daysOnMarket: 45,
    },
    {
      sellerId,
      agentId,
      title: 'Sun Siyam Vault Collection — Private Island Resort, Maldives',
      slug: slugify('sun-siyam-vault-collection-private-island-resort-maldives'),
      assetType: 'hotel',
      status: 'active',
      visibility: 'off_market',
      priceOnRequest: true,
      priceCurrency: 'USD',
      country: 'Maldives',
      city: 'South Malé Atoll',
      district: 'Private Island',
      coordinatesLat: '3.8520',
      coordinatesLng: '73.6312',
      sizeSqm: '220000',
      bedrooms: 65,
      bathrooms: 65,
      floors: 2,
      yearBuilt: 2019,
      description:
        'Sixty-five overwater and beach villas on a pristine private island in the South Malé Atoll. This off-market trophy resort delivers USD 28M revenue annually with a lean operating structure. Includes a 10-seat seaplane terminal, underwater restaurant, and direct MICE facilities. Price on application for qualified buyers only.',
      keyFeatures: [
        '65 Overwater Villas',
        'Seaplane Terminal',
        'Underwater Restaurant',
        'Private Island',
        'MICE Facilities',
        'USD 28M Annual Revenue',
      ],
      commercialData: { occupancyRate: 91, noi: 22000000, capRate: 7.1, revpar: 4800 },
      sellerMotivation: 'testing_market',
      titleDeedVerified: true,
      listingQualityScore: 98,
      qualityTier: 'platinum',
      daysOnMarket: 7,
    },
    {
      sellerId,
      title: "Hôtel de Paris — Belle Époque Palace Hotel, Monaco",
      slug: slugify('hotel-de-paris-belle-epoque-palace-hotel-monaco'),
      assetType: 'hotel',
      status: 'active',
      visibility: 'off_market',
      priceAmount: '950000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Monaco',
      city: 'Monte-Carlo',
      district: 'Place du Casino',
      coordinatesLat: '43.7396',
      coordinatesLng: '7.4272',
      sizeSqm: '28000',
      bedrooms: 207,
      bathrooms: 220,
      floors: 8,
      yearBuilt: 1864,
      description:
        "A once-in-a-generation opportunity to acquire one of Europe's most storied palace hotels in the heart of Monte-Carlo. 207 rooms and suites, 5 restaurants, a 3,500-year-old wine cellar, and direct access to the Casino de Monte-Carlo. Completely renovated 2019. Operating under the Société des Bains de Mer brand.",
      keyFeatures: [
        '207 Rooms & Suites',
        '5 Restaurants',
        '3500-Year Wine Cellar',
        'Casino Adjacency',
        'Renovated 2019',
        'SBM Brand',
      ],
      commercialData: { occupancyRate: 97, noi: 82000000, capRate: 8.6, revpar: 11500 },
      sellerMotivation: 'motivated',
      titleDeedVerified: true,
      listingQualityScore: 100,
      qualityTier: 'platinum',
      daysOnMarket: 3,
    },
    {
      sellerId,
      agentId,
      title: 'The Belgravia Collection — Freehold Hotel Investment, Mayfair',
      slug: slugify('belgravia-collection-freehold-hotel-mayfair-london'),
      assetType: 'hotel',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '380000000',
      priceCurrency: 'GBP',
      priceOnRequest: false,
      country: 'United Kingdom',
      city: 'London',
      district: 'Mayfair',
      coordinatesLat: '51.5074',
      coordinatesLng: '-0.1432',
      sizeSqm: '14200',
      bedrooms: 98,
      bathrooms: 112,
      floors: 9,
      yearBuilt: 1928,
      description:
        "A rare freehold opportunity in Mayfair — 98 keys across a beautifully restored Edwardian building. Consistently achieving £950+ ADR with a loyal base of ultra-high-net-worth repeat guests. Features a private members' club, cigar lounge, and dedicated butler floors. Unencumbered freehold title.",
      keyFeatures: [
        'Freehold Title',
        'Private Members Club',
        'Cigar Lounge',
        'Butler Service Floors',
        '£950+ ADR',
        'Edwardian Architecture',
      ],
      commercialData: { occupancyRate: 89, noi: 28000000, capRate: 7.4, revpar: 845 },
      sellerMotivation: 'fast_close',
      titleDeedVerified: true,
      listingQualityScore: 94,
      qualityTier: 'platinum',
      daysOnMarket: 21,
    },

    // ── 4 Palaces ─────────────────────────────────────────────────────────────
    {
      sellerId,
      title: 'Royal Najd Palace — Private Royal Compound, Riyadh',
      slug: slugify('royal-najd-palace-private-compound-riyadh'),
      assetType: 'palace',
      status: 'active',
      visibility: 'off_market',
      priceOnRequest: true,
      priceCurrency: 'SAR',
      country: 'Saudi Arabia',
      city: 'Riyadh',
      district: 'Al Malaz',
      coordinatesLat: '24.6877',
      coordinatesLng: '46.7219',
      sizeSqm: '85000',
      bedrooms: 48,
      bathrooms: 60,
      floors: 4,
      yearBuilt: 2008,
      description:
        "An extraordinary royal-grade compound spanning 85,000 sqm in Riyadh's most prestigious quarter. Custom-built to the highest Najdi architectural standards with 48 bedroom suites, a private mosque, equestrian facilities, and underground entertainment complex. Price strictly on application. Discretion assured.",
      keyFeatures: [
        '85,000 sqm Compound',
        'Private Mosque',
        'Equestrian Facilities',
        'Underground Entertainment',
        '48 Bedroom Suites',
        'Full Staff Quarters',
      ],
      sellerMotivation: 'testing_market',
      titleDeedVerified: true,
      listingQualityScore: 96,
      qualityTier: 'platinum',
      daysOnMarket: 5,
    },
    {
      sellerId,
      agentId,
      title: 'Dar Al Hana — Moorish Palace, Marrakech Medina',
      slug: slugify('dar-al-hana-moorish-palace-marrakech-medina'),
      assetType: 'palace',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '85000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Morocco',
      city: 'Marrakech',
      district: 'Medina',
      coordinatesLat: '31.6295',
      coordinatesLng: '-7.9811',
      sizeSqm: '12000',
      bedrooms: 24,
      bathrooms: 28,
      floors: 3,
      yearBuilt: 1897,
      description:
        'A masterwork of Moorish architecture spanning 12,000 sqm within the ancient walls of the Marrakech Medina. Dating to 1897, the palace features six internal courtyards, hand-painted zellige tilework, carved cedarwood ceilings, a hammam complex, and lush gardens fed by ancient water channels. Impeccably restored.',
      keyFeatures: [
        '6 Internal Courtyards',
        'Hand-Painted Zellige',
        'Cedarwood Ceilings',
        'Hammam Complex',
        'Ancient Gardens',
        'Medina Walls Location',
      ],
      sellerMotivation: 'price_flexible',
      titleDeedVerified: true,
      listingQualityScore: 91,
      qualityTier: 'platinum',
      daysOnMarket: 38,
    },
    {
      sellerId,
      title: 'Yıldız Sarayı Annex — Imperial Estate, Istanbul Bosphorus',
      slug: slugify('yildiz-sarayi-annex-imperial-estate-istanbul-bosphorus'),
      assetType: 'palace',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '250000000',
      priceCurrency: 'USD',
      priceOnRequest: false,
      country: 'Turkey',
      city: 'Istanbul',
      district: 'Beşiktaş',
      coordinatesLat: '41.0455',
      coordinatesLng: '29.0109',
      sizeSqm: '22000',
      bedrooms: 32,
      bathrooms: 38,
      floors: 3,
      yearBuilt: 1880,
      description:
        "An authentic Ottoman imperial-era estate on the European shores of the Bosphorus. This 22,000 sqm property features original 19th-century architecture, panoramic Bosphorus views, a private jetty for 6 vessels, and meticulously maintained historic interiors. One of Istanbul's last privately held imperial properties.",
      keyFeatures: [
        'Bosphorus Frontage',
        'Private Jetty (6 Vessels)',
        'Ottoman Architecture',
        '22,000 sqm Estate',
        'Historic Interiors',
        'Direct Sea Access',
      ],
      sellerMotivation: 'motivated',
      titleDeedVerified: true,
      listingQualityScore: 93,
      qualityTier: 'platinum',
      daysOnMarket: 15,
    },
    {
      sellerId,
      agentId,
      title: 'Palais Schwarzenberg West Wing — Baroque Palace, Vienna',
      slug: slugify('palais-schwarzenberg-west-wing-baroque-palace-vienna'),
      assetType: 'palace',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '180000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Austria',
      city: 'Vienna',
      district: 'Innere Stadt',
      coordinatesLat: '48.1949',
      coordinatesLng: '16.3782',
      sizeSqm: '9500',
      bedrooms: 18,
      bathrooms: 22,
      floors: 3,
      yearBuilt: 1697,
      description:
        "The west wing of one of Vienna's most celebrated baroque palaces, available separately for the first time in three centuries. Occupying 9,500 sqm across three magnificent floors, with 6.5m ceiling heights, original frescoes, and private gardens bordering the Belvedere. Monument status — eligible for significant Austrian heritage tax benefits.",
      keyFeatures: [
        '6.5m Ceiling Heights',
        'Original Frescoes',
        'Baroque Gardens',
        'Monument Status',
        'Heritage Tax Benefits',
        'Belvedere Adjacency',
      ],
      sellerMotivation: 'best_offers',
      titleDeedVerified: true,
      listingQualityScore: 97,
      qualityTier: 'platinum',
      daysOnMarket: 8,
    },

    // ── 4 Development Plots ───────────────────────────────────────────────────
    {
      sellerId,
      title: 'Palm Jebel Ali — 12-Hectare Freehold Seafront Plot',
      slug: slugify('palm-jebel-ali-12-hectare-freehold-seafront-plot-dubai'),
      assetType: 'development_plot',
      status: 'active',
      visibility: 'public',
      priceAmount: '180000000',
      priceCurrency: 'AED',
      priceOnRequest: false,
      country: 'United Arab Emirates',
      city: 'Dubai',
      district: 'Palm Jebel Ali',
      coordinatesLat: '25.0200',
      coordinatesLng: '55.0279',
      sizeSqm: '120000',
      description:
        "A premier 12-hectare freehold seafront development plot on Palm Jebel Ali, Dubai's newest mega-development. GFA permits mixed-use development up to 450,000 sqm including hotel, branded residences, and marina retail. All infrastructure in place. Projected completion of surrounding infrastructure: Q4 2026.",
      keyFeatures: [
        '12 Hectares',
        'Freehold Title',
        '450,000 sqm GFA',
        'Seafront',
        'Mixed-Use Permit',
        'Infrastructure Ready',
      ],
      sellerMotivation: 'fast_close',
      titleDeedVerified: true,
      listingQualityScore: 88,
      qualityTier: 'gold',
      daysOnMarket: 22,
    },
    {
      sellerId,
      agentId,
      title: 'NEOM Luxury Tourism Zone — Development Plot, Tabuk',
      slug: slugify('neom-luxury-tourism-zone-development-plot-tabuk-riyadh'),
      assetType: 'development_plot',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '95000000',
      priceCurrency: 'SAR',
      priceOnRequest: false,
      country: 'Saudi Arabia',
      city: 'Tabuk',
      district: 'NEOM Zone B',
      coordinatesLat: '28.0339',
      coordinatesLng: '35.5219',
      sizeSqm: '500000',
      description:
        "A 50-hectare luxury tourism development plot within the NEOM Vision 2030 zone. Designated for ultra-luxury eco-resort development with Red Sea frontage. Development partner agreements pre-negotiated with NEOM authority. Exceptional opportunity for first-mover advantage in one of the world's largest planned developments.",
      keyFeatures: [
        '50 Hectares',
        'Red Sea Frontage',
        'NEOM Designation',
        'Eco-Resort Permit',
        'Vision 2030',
        'Pre-Negotiated Agreements',
      ],
      sellerMotivation: 'motivated',
      titleDeedVerified: true,
      listingQualityScore: 85,
      qualityTier: 'gold',
      daysOnMarket: 31,
    },
    {
      sellerId,
      title: 'New Alamein — Mixed-Use Waterfront Plot, Mediterranean Coast',
      slug: slugify('new-alamein-mixed-use-waterfront-plot-mediterranean-egypt'),
      assetType: 'development_plot',
      status: 'active',
      visibility: 'public',
      priceAmount: '120000000',
      priceCurrency: 'USD',
      priceOnRequest: false,
      country: 'Egypt',
      city: 'New Alamein',
      district: 'New Alamein City',
      coordinatesLat: '30.8349',
      coordinatesLng: '28.9483',
      sizeSqm: '300000',
      description:
        "Thirty hectares of prime Mediterranean waterfront within Egypt's flagship New Alamein development. The plot carries a mixed-use permit covering 6-star hotel, branded residences, and beach club. Direct access to the new international marina. One of Egypt's largest remaining trophy coastal development opportunities.",
      keyFeatures: [
        '30 Hectares',
        'Mediterranean Frontage',
        '6-Star Hotel Permit',
        'Marina Access',
        'Mixed-Use',
        'New Alamein Master Plan',
      ],
      sellerMotivation: 'price_flexible',
      titleDeedVerified: false,
      listingQualityScore: 78,
      qualityTier: 'gold',
      daysOnMarket: 56,
    },
    {
      sellerId,
      agentId,
      title: 'Athenian Riviera — 4-Hectare Development Site, Glyfada',
      slug: slugify('athenian-riviera-development-site-glyfada-athens-greece'),
      assetType: 'development_plot',
      status: 'active',
      visibility: 'public',
      priceAmount: '45000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Greece',
      city: 'Athens',
      district: 'Glyfada',
      coordinatesLat: '37.8836',
      coordinatesLng: '23.7516',
      sizeSqm: '40000',
      description:
        'An exceptional 4-hectare site on the Athenian Riviera in Glyfada, minutes from Athens International Airport. Golden Visa eligible (€250K minimum investment). Permit approved for luxury residential complex of 48 units or boutique hotel up to 80 keys. Existing 3,200 sqm structure can be incorporated.',
      keyFeatures: [
        'Golden Visa Eligible',
        'Permit Approved',
        'Sea Views',
        'Airport Proximity',
        'EU Golden Visa',
        'Existing Structure',
      ],
      sellerMotivation: 'fast_close',
      titleDeedVerified: true,
      listingQualityScore: 82,
      qualityTier: 'gold',
      daysOnMarket: 44,
    },

    // ── 4 Private Islands ─────────────────────────────────────────────────────
    {
      sellerId,
      title: 'Velaa Faru — 8-Hectare Private Island, North Malé Atoll',
      slug: slugify('velaa-faru-private-island-north-male-atoll-maldives'),
      assetType: 'private_island',
      status: 'active',
      visibility: 'off_market',
      priceAmount: '280000000',
      priceCurrency: 'USD',
      priceOnRequest: false,
      country: 'Maldives',
      city: 'North Malé Atoll',
      district: 'Private Island',
      coordinatesLat: '4.8515',
      coordinatesLng: '73.5316',
      sizeSqm: '80000',
      description:
        'An 8-hectare private island in the North Malé Atoll, 25 minutes from Malé by speedboat. The island includes a fully operational 32-villa resort generating USD 18M annual revenue, helicopter pad, private submarine, decompression chamber, and extensive marine research facilities. Title fully clear.',
      keyFeatures: [
        '8 Hectares',
        '32-Villa Resort',
        'Helicopter Pad',
        'Private Submarine',
        'Marine Research Facilities',
        'USD 18M Annual Revenue',
      ],
      commercialData: { occupancyRate: 89, noi: 14000000, capRate: 5.0 },
      sellerMotivation: 'testing_market',
      titleDeedVerified: true,
      listingQualityScore: 97,
      qualityTier: 'platinum',
      daysOnMarket: 4,
    },
    {
      sellerId,
      agentId,
      title: 'Aegean Dream — Undeveloped Private Island, Cyclades',
      slug: slugify('aegean-dream-undeveloped-private-island-cyclades-greece'),
      assetType: 'private_island',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '95000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Greece',
      city: 'Cyclades',
      district: 'Aegean Islands',
      coordinatesLat: '37.0179',
      coordinatesLng: '25.0952',
      sizeSqm: '1200000',
      description:
        'A 120-hectare private island in the Cyclades archipelago, 15 nautical miles from Mykonos. Greek freehold title with EU Golden Visa eligibility. Planning permission for a 24-villa ultra-luxury eco-resort has been obtained. Three natural harbors, two sandy beaches, and year-round fresh water springs.',
      keyFeatures: [
        '120 Hectares',
        'EU Freehold Title',
        'Resort Planning Permit',
        '3 Natural Harbors',
        'Year-Round Spring Water',
        'Mykonos Proximity',
      ],
      sellerMotivation: 'best_offers',
      titleDeedVerified: true,
      listingQualityScore: 93,
      qualityTier: 'platinum',
      daysOnMarket: 19,
    },
    {
      sellerId,
      title: 'Emerald Cay — Fully Operational Private Island Resort, Turks & Caicos',
      slug: slugify('emerald-cay-private-island-resort-turks-caicos-caribbean'),
      assetType: 'private_island',
      status: 'active',
      visibility: 'off_market',
      priceOnRequest: true,
      priceCurrency: 'USD',
      country: 'Turks and Caicos',
      city: 'Providenciales',
      district: 'Grace Bay',
      coordinatesLat: '21.7749',
      coordinatesLng: '-72.2128',
      sizeSqm: '180000',
      description:
        'A turn-key private island resort on the turquoise waters of Turks & Caicos. 16 overwater bungalows, 8 beachfront villas, a world-class dive center, and a private airstrip for light aircraft. Revenue: USD 22M annually. Staff of 85. Permanent residency pathway for purchaser included. Price on application.',
      keyFeatures: [
        'Private Airstrip',
        '16 Overwater Bungalows',
        'Dive Center',
        'Staff of 85',
        'USD 22M Revenue',
        'Residency Pathway',
      ],
      commercialData: { occupancyRate: 93, noi: 15000000, capRate: 6.8 },
      sellerMotivation: 'motivated',
      titleDeedVerified: true,
      listingQualityScore: 99,
      qualityTier: 'platinum',
      daysOnMarket: 2,
    },
    {
      sellerId,
      agentId,
      title: 'Ko Vault — Private Island Development Site, Gulf of Thailand',
      slug: slugify('ko-vault-private-island-development-site-gulf-thailand'),
      assetType: 'private_island',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '45000000',
      priceCurrency: 'USD',
      priceOnRequest: false,
      country: 'Thailand',
      city: 'Koh Samui',
      district: 'Gulf of Thailand',
      coordinatesLat: '9.5399',
      coordinatesLng: '100.0613',
      sizeSqm: '280000',
      description:
        'A pristine 28-hectare undeveloped island in the Gulf of Thailand, 8 nautical miles from Koh Samui. Thai leasehold structure (90-year term) with a full resort development BOI permit already approved. White sand beaches on three sides, protected bay, and existing jetty.',
      keyFeatures: [
        '28 Hectares',
        '90-Year Leasehold',
        'BOI Resort Permit',
        'White Sand Beaches',
        'Protected Bay',
        'Existing Jetty',
      ],
      sellerMotivation: 'fast_close',
      titleDeedVerified: true,
      listingQualityScore: 86,
      qualityTier: 'gold',
      daysOnMarket: 33,
    },

    // ── 4 Penthouse Towers ────────────────────────────────────────────────────
    {
      sellerId,
      title: 'The Royal Atlantis Sky Villa — Full Floor Penthouse, The Palm',
      slug: slugify('royal-atlantis-sky-villa-full-floor-penthouse-palm-dubai'),
      assetType: 'penthouse_tower',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '150000000',
      priceCurrency: 'AED',
      priceOnRequest: false,
      country: 'United Arab Emirates',
      city: 'Dubai',
      district: 'The Palm Jumeirah',
      coordinatesLat: '25.1288',
      coordinatesLng: '55.1173',
      sizeSqm: '2200',
      bedrooms: 7,
      bathrooms: 9,
      floors: 1,
      yearBuilt: 2022,
      description:
        'The most coveted residence in the Middle East — the full-floor Sky Villa atop The Royal Atlantis. 2,200 sqm of pure luxury with a private 600 sqm terrace, 25m infinity pool, and 360° views of Palm Jumeirah, the Arabian Gulf, and Dubai skyline. Direct elevator from private underground garage. All Atlantis amenities included.',
      keyFeatures: [
        '2,200 sqm',
        '600 sqm Private Terrace',
        '25m Infinity Pool',
        '360° Views',
        'Private Elevator',
        'All Atlantis Amenities',
      ],
      sellerMotivation: 'best_offers',
      titleDeedVerified: true,
      listingQualityScore: 98,
      qualityTier: 'platinum',
      daysOnMarket: 11,
    },
    {
      sellerId,
      agentId,
      title: 'One Hyde Park — Triple Penthouse, Knightsbridge',
      slug: slugify('one-hyde-park-triple-penthouse-knightsbridge-london'),
      assetType: 'penthouse_tower',
      status: 'active',
      visibility: 'off_market',
      priceAmount: '175000000',
      priceCurrency: 'GBP',
      priceOnRequest: false,
      country: 'United Kingdom',
      city: 'London',
      district: 'Knightsbridge',
      coordinatesLat: '51.5027',
      coordinatesLng: '-0.1631',
      sizeSqm: '1850',
      bedrooms: 6,
      bathrooms: 8,
      floors: 3,
      yearBuilt: 2011,
      description:
        "Three combined apartments totalling 1,850 sqm at the pinnacle of One Hyde Park — the world's most expensive residential building. Triple-height reception, private cinema, wine vault, and direct underground connection to the Mandarin Oriental hotel and spa. Discreet concierge, SAS-trained security, and armored doors throughout.",
      keyFeatures: [
        '1,850 sqm',
        'SAS Security',
        'Private Cinema',
        'Wine Vault',
        'Mandarin Oriental Access',
        'Armored Doors',
      ],
      sellerMotivation: 'testing_market',
      titleDeedVerified: true,
      listingQualityScore: 100,
      qualityTier: 'platinum',
      daysOnMarket: 6,
    },
    {
      sellerId,
      title: '432 Park Avenue — Full Floor Residence, Midtown Manhattan',
      slug: slugify('432-park-avenue-full-floor-residence-midtown-manhattan-nyc'),
      assetType: 'penthouse_tower',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '82000000',
      priceCurrency: 'USD',
      priceOnRequest: false,
      country: 'United States',
      city: 'New York',
      district: 'Midtown Manhattan',
      coordinatesLat: '40.7617',
      coordinatesLng: '-73.9716',
      sizeSqm: '1260',
      bedrooms: 5,
      bathrooms: 6,
      floors: 1,
      yearBuilt: 2015,
      description:
        "A full-floor residence on the 87th floor of 432 Park Avenue — the tallest residential tower in the Western Hemisphere. Unobstructed views of Central Park, both rivers, and the entire Manhattan skyline. 4.5m ceiling heights, white marble finishes throughout, private elevator lobby. Building amenities: 75ft pool, spa, private restaurant.",
      keyFeatures: [
        '4.5m Ceilings',
        'Central Park Views',
        'Private Elevator Lobby',
        '75ft Pool',
        'Private Restaurant',
        'Tallest Residential in Western Hemisphere',
      ],
      sellerMotivation: 'price_flexible',
      titleDeedVerified: true,
      listingQualityScore: 95,
      qualityTier: 'platinum',
      daysOnMarket: 27,
    },
    {
      sellerId,
      agentId,
      title: 'Wallich Residence — Pinnacle Penthouse, Tanjong Pagar',
      slug: slugify('wallich-residence-pinnacle-penthouse-tanjong-pagar-singapore'),
      assetType: 'penthouse_tower',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '62000000',
      priceCurrency: 'SGD',
      priceOnRequest: false,
      country: 'Singapore',
      city: 'Singapore',
      district: 'Tanjong Pagar',
      coordinatesLat: '1.2756',
      coordinatesLng: '103.8453',
      sizeSqm: '1410',
      bedrooms: 5,
      bathrooms: 6,
      floors: 3,
      yearBuilt: 2018,
      description:
        "The penthouse of Wallich Residence, Singapore's tallest building. Triplex layout across floors 62–64 with a private 200 sqm sky terrace. Views spanning all of Singapore, the Strait of Malacca, and the Indonesian islands on clear days. Integrated with the Guoco Tower — Singapore's premier mixed-use development.",
      keyFeatures: [
        'Triplex Layout',
        'Sky Terrace 200 sqm',
        '62nd-64th Floor',
        'Singapore City Views',
        'Guoco Tower Integration',
        'Premium Finishes',
      ],
      sellerMotivation: 'motivated',
      titleDeedVerified: true,
      listingQualityScore: 93,
      qualityTier: 'platinum',
      daysOnMarket: 16,
    },

    // ── 4 Villas ──────────────────────────────────────────────────────────────
    {
      sellerId,
      title: 'Emirates Hills Lakefront Mega Villa — Golf Course Estate',
      slug: slugify('emirates-hills-lakefront-mega-villa-golf-course-estate-dubai'),
      assetType: 'villa',
      status: 'active',
      visibility: 'public',
      priceAmount: '120000000',
      priceCurrency: 'AED',
      priceOnRequest: false,
      country: 'United Arab Emirates',
      city: 'Dubai',
      district: 'Emirates Hills',
      coordinatesLat: '25.0831',
      coordinatesLng: '55.1611',
      sizeSqm: '3800',
      bedrooms: 9,
      bathrooms: 12,
      floors: 3,
      yearBuilt: 2020,
      description:
        'The crown jewel of Emirates Hills — a 3,800 sqm contemporary mansion with direct lakefront and Montgomerie golf course frontage. Nine bedroom suites, home cinema, spa with 25m indoor pool, and a 12-car underground garage. Smart home automation throughout. Two separate staff quarters and a private helipad.',
      keyFeatures: [
        '3,800 sqm BUA',
        'Lakefront + Golf Frontage',
        '25m Indoor Pool',
        'Home Cinema',
        '12-Car Garage',
        'Private Helipad',
      ],
      sellerMotivation: 'best_offers',
      titleDeedVerified: true,
      listingQualityScore: 96,
      qualityTier: 'platinum',
      daysOnMarket: 9,
    },
    {
      sellerId,
      agentId,
      title: 'Villa Belle Mer — Cliff-Top Estate, Cap Ferrat',
      slug: slugify('villa-belle-mer-cliff-top-estate-cap-ferrat-nice-france'),
      assetType: 'villa',
      status: 'active',
      visibility: 'off_market',
      priceAmount: '95000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'France',
      city: 'Nice',
      district: 'Cap Ferrat',
      coordinatesLat: '43.6878',
      coordinatesLng: '7.3297',
      sizeSqm: '2100',
      bedrooms: 8,
      bathrooms: 10,
      floors: 3,
      yearBuilt: 1932,
      description:
        'A magnificent Belle Époque villa perched on the cliffs of Cap Ferrat with 180° Mediterranean views. Built in 1932 and meticulously restored to its original grandeur. Private access to the sea with a boat house for two vessels, heated infinity pool, and 5,000 sqm of formal gardens. Seven staff quarters.',
      keyFeatures: [
        '180° Sea Views',
        'Belle Époque Architecture',
        'Private Sea Access',
        'Boathouse',
        'Infinity Pool',
        '5,000 sqm Gardens',
      ],
      sellerMotivation: 'testing_market',
      titleDeedVerified: true,
      listingQualityScore: 94,
      qualityTier: 'platinum',
      daysOnMarket: 14,
    },
    {
      sellerId,
      title: 'Finca Can Vault — Ultra-Private Ibiza Estate',
      slug: slugify('finca-can-vault-ultra-private-ibiza-estate-spain'),
      assetType: 'villa',
      status: 'active',
      visibility: 'verified_buyers',
      priceAmount: '48000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Spain',
      city: 'Ibiza',
      district: 'San José',
      coordinatesLat: '38.9027',
      coordinatesLng: '1.2882',
      sizeSqm: '1600',
      bedrooms: 7,
      bathrooms: 8,
      floors: 2,
      yearBuilt: 2017,
      description:
        'A stunning 10-hectare Ibiza estate with an ultra-contemporary 1,600 sqm villa offering complete privacy. Sea views from every room, 30m infinity pool, outdoor cinema, helipad, and professional DJ booth. Rental income of €2.5M annually when available. Gated access with professional security infrastructure.',
      keyFeatures: [
        '10 Hectares',
        '30m Infinity Pool',
        'Helipad',
        'Professional DJ Booth',
        'Sea Views',
        '€2.5M Rental Income',
      ],
      sellerMotivation: 'fast_close',
      titleDeedVerified: true,
      listingQualityScore: 90,
      qualityTier: 'platinum',
      daysOnMarket: 26,
    },
    {
      sellerId,
      agentId,
      title: 'Podere della Vigna — Tuscan Wine Estate & Villa',
      slug: slugify('podere-della-vigna-tuscan-wine-estate-villa-tuscany-italy'),
      assetType: 'villa',
      status: 'active',
      visibility: 'public',
      priceAmount: '32000000',
      priceCurrency: 'EUR',
      priceOnRequest: false,
      country: 'Italy',
      city: 'Tuscany',
      district: 'Chianti Classico',
      coordinatesLat: '43.5673',
      coordinatesLng: '11.2921',
      sizeSqm: '1800',
      bedrooms: 10,
      bathrooms: 12,
      floors: 3,
      yearBuilt: 1640,
      description:
        "A 17th-century Tuscan estate encompassing a 1,800 sqm restored villa and 25 hectares of Chianti Classico vineyards. Annual wine production of 80,000 bottles under a recognised DOC label with €1.2M revenue. Olive grove, private chapel, and a 2,000 sqm agriturismo generating additional income. Complete with working winery.",
      keyFeatures: [
        '25ha Chianti Classico',
        'Working Winery',
        '80,000 Bottle Production',
        'DOC Classification',
        'Agriturismo Revenue',
        '17th Century Architecture',
      ],
      commercialData: { noi: 1800000, occupancyRate: null, capRate: null },
      sellerMotivation: 'price_flexible',
      titleDeedVerified: true,
      listingQualityScore: 88,
      qualityTier: 'gold',
      daysOnMarket: 52,
    },
  ];

  console.log(`Inserting ${listingsData.length} listings...`);

  for (const listing of listingsData) {
    try {
      const text = `${listing.title} ${listing.description ?? ''} ${listing.city} ${listing.country}`;
      const embedding = await mockGetEmbedding(text);

      // Sanitise any trailing commas that leaked into numeric fields
      if (listing.sizeSqm) {
        listing.sizeSqm = listing.sizeSqm.toString().replace(/,/g, '');
      }

      await db.insert(schema.listings).values({ ...listing, embedding }).onConflictDoNothing();
      console.log(`  + ${listing.title.slice(0, 60)}`);
    } catch (err) {
      console.error(`  x Failed: ${listing.title.slice(0, 60)}`, err);
    }
  }

  console.log('\nSeed complete!');
  await client.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
