apiVersion: v1
kind: Namespace
metadata:
  name: vault-dev
  labels:
    environment: dev
    app: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-staging
  labels:
    environment: staging
    app: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-prod
  labels:
    environment: production
    app: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-monitoring
  labels:
    app: vault
