apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app: vault
    service: notification-service
data:
  PORT: "3007"
  NODE_ENV: "production"
  MOCK_SERVICES: "false"
  LOG_LEVEL: "info"
  EMAIL_FROM: "noreply@vault.ae"
  REDIS_EVENT_CHANNEL_PREFIX: "vault:"
