apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patches/staging-image.yaml
  - path: patches/staging-config.yaml
  - path: patches/staging-ingress.yaml
  - path: patches/staging-platform.yaml
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: ConfigMap
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: Secret
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: /metadata/namespace
        value: vault-staging
